platform :tvos, '12.0'
workspace 'RNAppleTVTalk'
project 'RNAppleTVTalk.xcodeproj'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'RNAppleTVTalk' do
  # Uncomment for Swift
  # use_frameworks!

  config = use_native_modules!

  use_react_native!(:path => "../node_modules/react-native")

end

