platform :tvos, '12.0'
workspace 'RNAppleTVTalk'
project 'RNAppleTVTalk.xcodeproj'

require_relative '../node_modules/react-native/scripts/autolink-ios'

target 'RNAppleTVTalk' do
  # Uncomment for Swift
  # use_frameworks!

  use_react_native!(path: "../node_modules/react-native")

  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'react-native-video', :path => '../node_modules/react-native-video'
  pod 'RNTVOSController', :path => '../node_modules/react-native-tvos-controller'
end

